config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "newsroom", to: "application#newsroom"
  get "dashboard/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "application#newsroom"
  resources :book_reviews do 
    collection do 
      get :fiction
      get :history
      get :non_fiction
      get :mystery
      get :science
      get :romance
      get :spirituality
      get :fantasy
    end
  end
  resources :game_reviews
  resources :articles do
    collection do 
      get :culture
      get :travel
      get :sport
    end 
  end
  resources :news do 
    collection do 
      get :world
      get :sport
      get :regional
      get :tech
      get :business
      get :entertainment
    end
    member do
      get :comments
      post :news_comment
    end
  end
end

app/views/partials/_article_form.html.erb
<div class="general-review-form">
    <center><h2><%= action %></h2></center>
    <%= form_for(@article, url: url) do |f| %>
        <%= render "devise/shared/error_messages", resource: @article %>
        
        <div class="field">
            <%= f.label :title, class: "" %>
            <%= f.text_field :title, class: "" %>
        </div>

        <div class="field">
            <%= f.label :author, class: "" %>
            <%= f.text_field :author, class: "" %>
        </div>

        <div class="field">
            <%= f.label "Attach", class: "" %>
            <%= f.file_field :avatar %>
            <% if @article.avatar.present? %>
                <p>Currently uploaded: <%= @article.avatar.file.filename %></p>
            <% end %>
        </div>

        <div class="field">
            <%= f.label :published, class: "" %>
            <%= f.date_field :published, class: "" %>
        </div>

        <div class="field">
            <%= f.label :tag, class: ""  %>
            <%= f.select :tag, options_for_select(['Science', 'Travel', 'Sport','Culture', 'Business', 'Innovation', 'Not Specified'], {selected: @article.tag}), { prompt: " -- Select One -- "}, { class: "select-field", placeholder:" " } %> 
        </div>

        <div class="field">
            <%= f.label :short_description, class: "" %>
            <%= f.text_area :short_description, class: "", rows: 3, cols: 95 %>  
        </div>

        <div class="field">
            <%= f.label :content %>
            <%= f.rich_text_area :content %>
        </div>

        <div class="actions">   
            <% if action == "new" %>
                <%= f.submit "Create", class: "", id: "" %>
            <% else %>
                <%= f.submit "Update", class: "", id: "" %>
            <% end %>
        </div>

    <% end %>
</div>

app/views/partials/_article_index.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <div class="sub-heading-navbar">
            <%= tabs_tag :namespace => :navigation do |tab| %>
                <%= tab.culture 'Culture', culture_articles_path, class: "child-navbar-links" %>
                <%= tab.sport 'Sport', sport_articles_path, class: "child-navbar-links" %>
                <%= tab.travel 'Travel', travel_articles_path, class: "child-navbar-links" %>
            <% end %>
        </div>
        <% if current_user.role == "Admin" %>
            <div class="add-new-container new-article">
                <%= icon "plus" %>
                <span><%= link_to "Add Article", new_article_path, class: "add-new", data: { turbo: false} %></span>
            </div>
        <% end %>
        <% if action == "index" %>
            <div class="latest-articles">
                <div class="latest-article-heading">
                    <h4> What's New ? </h4>
                </div>
                <div class="latest-articles-list">
                    <% @latest_articles.each do |latest| %>
                        <div class="latest-individual-headline">
                            <%= link_to article_path(latest), class: "whats-new-link", data: { turbo: false} do %>
                                <h3> <%= latest.title %> </h3>  
                            <% end %>  
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
        <div class="general-main-content">
            <div class="left-main-content article-card-content">
                <% @articles.each do |article| %>
                    <%= link_to article_path(article), class: "full-article-link", data: { turbo: false} do %>    
                        <div class="article-card">
                            <div class="article-card-image"><%= image_tag article.avatar.url, class: "article-image" %></div>
                            <div class="article-card-container">
                                <h2> <%= article.title %></h2>
                                <p> <%= article.short_description %></p>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
            <div class="right-main-content index-page-sidebar-ad">
                <p>ADVERTISEMENT</p>
                <%= image_tag "heinze-ad.jpg", class: "sidebar-ad" %>
            </div>
        </div>
    </main>
    <%= render "partials/common_footer" %>
</body>

app/views/partials/_book_review_form.html.erb
<div class="general-review-form">
    <center><h2><%= action %></h2></center>
    <%= form_for(@book_review, url: url) do |f| %>
        <%= render "devise/shared/error_messages", resource: @book_review %>
        
        <div class="field">
            <%= f.label :title, class: "" %>
            <%= f.text_field :title, class: "" %>
        </div>

        <div class="field">
            <%= f.label :author, class: "" %>
            <%= f.text_field :author, class: "" %>
        </div>

        <div class="field">
            <%= f.label "Attach", class: "" %>
            <%= f.file_field :avatar, class: "" %>
            <% if @book_review.avatar.present? %>
                <p>Currently uploaded: <%= @book_review.avatar.file.filename %></p>
            <% end %>
        </div>
        
        <div class="field">
            <%= f.label :rating, class: "" %>
            <%= f.number_field :rating, class: "",step: "any", min: 0, max: 5 %>  
        </div>

        <div class="field">
            <%= f.label :published, class: "" %>
            <%= f.date_field :published, class: "" %>
        </div>

        <div class="field">
            <%= f.label :genre, class: ""  %>
            <%= f.select :genre, options_for_select(['Fiction', 'Non-Fiction', 'Fantasy','Mystery', 'History', 'Science','Romance', 'Spirituality', 'Technology','Horror', 'Not Specified'], {selected: @book_review.genre}), { prompt: " -- Select One -- "}, { class: "select-field", placeholder:" " } %>
            
        </div>

        <div class="field">
            <%= f.label :review, class: "" %>
            <%= f.rich_text_area :review, class: "", rows: 15, cols: 95 %>
        </div>

        <div class="actions">
            <% if action == "new" %>
                <%= f.submit "Create", class: "", id: "" %>
            <% else %>
                <%= f.submit "Update", class: "", id: "" %>
            <% end %>
        </div>

    <% end %>
</div>

app/views/partials/_book_review_index.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <div class="sub-heading-header">
            <div class="tab-header">
                <h3> Book Reviews</h3>
            </div>
            <% if current_user.role == "Admin" %>
                <div class="add-new-container">
                    <%= icon "plus" %>
                    <span><%= link_to "Add Review", new_book_review_path, class: "add-new", data: { turbo: false} %></span>
                </div>
            <% end %>
        </div>
        <div class="general-main-content">
            <div class="left-main-content book-review-content">
                <% @book_reviews.each do |review| %>
                    <%= link_to book_review_path(review), class: "book-full-review-link", data: { turbo: false} do %>    
                        <div class="book-card">
                            <div class="book-card-image"><%= image_tag review.avatar.url, class: "book-image" %></div>
                            <div class="book-card-content">
                                <h4>by <%= review.author %></h4>
                                <p> <%= render_stars(review.rating) %></p>
                            </div>
                        </div>
                    <% end %>
                <% end %>
                <%= paginate @book_reviews %>
            </div>
            <div class="right-main-content">
                <div class="tab-heading-description">
                    <% if action != "index" %>    
                        <h3> <%= action.camelize %> </h3>
                    <% else %>
                        <h3> About </h3>
                    <% end %>
                    <p> <%= genre_description(action) %> </p>
                </div>
                <div class="sidebar-content">
                    <div class="sidebar-sub-header">
                        <h2> Categories </h2>
                    </div>
                    <div class="books-navbar">   
                        <%= tabs_tag :namespace => :navigation do |tab| %>
                            <%= tab.index 'All Books', book_reviews_path, class: "book-links" %>
                            <%= tab.fiction 'Fiction', fiction_book_reviews_path, class: "book-links" %>
                            <%= tab.history 'History', history_book_reviews_path, class: "book-links" %>
                            <%= tab.non_fiction 'Non-Fiction', non_fiction_book_reviews_path, class: "book-links" %>
                            <%= tab.mystery 'Mystery', mystery_book_reviews_path, class: "book-links" %>
                            <%= tab.science 'Science', science_book_reviews_path, class: "book-links" %>
                            <%= tab.romance 'Romance', romance_book_reviews_path, class: "book-links" %>
                            <%= tab.spirituality 'Spirituality', spirituality_book_reviews_path, class: "book-links" %>
                            <%= tab.fantasy 'Fantasy', fantasy_book_reviews_path, class: "book-links" %>
                        <% end %>
                    </div>
                    <div class="right-main-content index-page-sidebar-ad">
                        <p>ADVERTISEMENT</p>
                        <%= image_tag "amul-ad.jpeg", class: "sidebar-ad" %>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <%= render "partials/common_footer" %>
</body>

app/views/partials/_common_footer.html.erb
<div class="common-footer">
    <h3 class="letter-heading">
        <% "NEWSROOM".each_char do |char| %>
            <span><%= char %></span>
        <% end %>
    </h3>
    <p> © Copyright 2025 Newsroom - Vijay DA. All rights reserved. Newsroom is not responsible for the content of external sites.</p>
</div>

app/views/partials/_common_header.html.erb
<div class="dashboard-container">
    <header class="dashboard-heading">
        <div class="dashboard-header-content dashboard-date-field">
            <%= Date.today.strftime("%B %e, %Y") %>
        </div>
        <div class="dashboard-header-content dashboard-header">
            <%= link_to newsroom_path, class: "dashboard-header-link", data: { turbo: false} do %>
                <h1 class="letter-heading">
                    <% "NEWSROOM".each_char do |char| %>
                        <span><%= char %></span>
                    <% end %>
                </h1>
            <% end %>    
        </div>
        <div class="dashboard-header-content dashboard-header account-links">
            <div class="user-account">
                <%= icon "square-user-round" %>
                <span><%= link_to current_user.first_name, edit_user_registration_path, class: "user-account-link", data: { turbo_frame: "modal" } %></span>
            </div>
            <%= link_to "Logout", destroy_user_session_path, class: "logout-link", data: { turbo_method: :delete } %>
        </div>
    </header>
    <div class="dashboard-navbar">
        <%= tabs_tag(:builder => CustomTabsBuilder) do |tab| %>
            <%= tab.home 'Home', dashboard_home_path, class: "dashboard-links" %>
            <%= tab.news 'News', news_index_path, class: "dashboard-links" %>
            <%= tab.articles 'Articles', articles_path, class: "dashboard-links" %>
            <%= tab.game_reviews 'Game Reviews', game_reviews_path, class: "dashboard-links" %>
            <%= tab.book_reviews 'Book Reviews', book_reviews_path, class: "dashboard-links" %>
        <% end %>
    </div>
</div>  

app/views/partials/_game_review_form.html.erb
<div class="general-review-form">
    <center><h2><%= action %></h2></center>
    <%= form_for(@game_review, url: url) do |f| %>
        <%= render "devise/shared/error_messages", resource: @game_review %>
        
        
        <div class="field">
            <%= f.label :title, class: "" %>
            <%= f.text_field :title, class: "" %>
        </div>

        <div class="field">
            <%= f.label "Attach", class: "" %>
            <%= f.file_field :avatar, class: "" %>
            <% if @game_review.avatar.present? %>
                <p>Currently uploaded: <%= @game_review.avatar.file.filename %></p>
            <% end %>
        </div>
        
        <div class="field">
            <%= f.label :rating, class: "" %>
            <%= f.number_field :rating, class: "", min: 0, max: 100 %>  
        </div>

        <div class="field">
            <%= f.label :release, class: "" %>
            <%= f.date_field :release, class: "" %>
        </div>
        

        <div class="field">
            <%= f.label :short_description, class: "" %>
            <%= f.text_area :short_description, class: "", rows: 4, cols: 95 %>
        </div>

        <div class="field">
            <%= f.label :review, class: "" %>
            <%= f.rich_text_area :review, class: "", rows: 15, cols: 95 %>
        </div>

        <div class="actions">
            <% if action == "new" %>
                <%= f.submit "Create", class: "", id: "" %>
            <% else %>
                <%= f.submit "Update", class: "", id: "" %>
            <% end %>
        </div>

    <% end %>
</div>

app/views/partials/_news_form.html.erb
<div class="general-review-form">
    <center><h2><%= action %></h2></center>
    <%= form_for(@news, url: url) do |f| %>
        <%= render "devise/shared/error_messages", resource: @news %>
        
        <div class="field">
            <%= f.label :headline, class: "" %>
            <%= f.text_field :headline, class: "" %>
        </div>

        <div class="field">
            <%= f.label "Attach", class: "" %>
            <%= f.file_field :avatar %>
            <% if @news.avatar.present? %>
                <p>Currently uploaded: <%= @news.avatar.file.filename %></p>
            <% end %>
        </div>

        <div class="field">
            <%= f.label :published_on, class: "" %>
            <%= f.datetime_field :published_on, class: "" %>
        </div>

        <div class="checkbox-field">
            <%= f.checkbox :main_featured, class: "inline-checkbox" %>
            <%= f.label :main_featured, class: "inline-label"  %>
        </div>

        <div class="checkbox-field">
            <%= f.checkbox :featured, class: "inline-checkbox" %>
            <%= f.label :featured, class: "inline-label"  %>
        </div>

        <div class="field">
            <%= f.label :tag, class: ""  %>
            <%= f.select :tag, options_for_select(['World', 'Regional', 'Sport', 'Business', 'Tech', 'Entertainment', 'Not Specified'], {selected: @news.tag}), { prompt: " -- Select One -- "}, { class: "select-field", placeholder:" " } %> 
        </div>

        <div class="field">
            <%= f.label :short_description, class: "" %>
            <%= f.text_area :short_description, class: "", rows: 3, cols: 95 %>  
        </div>

        <div class="field">
            <%= f.label :content %>
            <%= f.rich_text_area :content %>
        </div>

        <div class="actions">   
            <% if action == "New" %>
                <%= f.submit "Create", class: "", id: "" %>
            <% else %>
                <%= f.submit "Update", class: "", id: "" %>
            <% end %>
        </div>

    <% end %>
</div>

app/views/partials/_news_index.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main>
        <div class="sub-heading-navbar">
            <%= tabs_tag :namespace => :navigation do |tab| %>
                <%= tab.world 'World', world_news_index_path, class: "child-navbar-links" %>
                <%= tab.sport 'Sport', sport_news_index_path, class: "child-navbar-links" %>
                <%= tab.regional 'Regional', regional_news_index_path, class: "child-navbar-links" %>
                <%= tab.tech 'Tech', tech_news_index_path, class: "child-navbar-links" %>
                <%= tab.business 'Business', business_news_index_path, class: "child-navbar-links" %>
                <%= tab.entertainment 'Entertainment', entertainment_news_index_path, class: "child-navbar-links" %>
            <% end %>
        </div>
        <% if current_user.role == "Admin" %>
            <div class="add-new-container create-news">
                <%= icon "plus" %>
                <span><%= link_to "Add News", new_news_path, class: "add-new", data: { turbo: false} %></span>
            </div>
        <% end %>

        <div class="tab-header">
            <% unless action == "index" %>
                <h3> <%= action.camelize %> </h3>
            <% else %>
                <h3> News </h3>
            <% end %>
        </div>
        <% if @main_featured.present? %>          
            <div class="news-main-layout">
                <div class="news-leftside-content">    
                    <div class="main-featured-content">
                        <%= link_to news_path(@main_featured), class: "main-featured-news-link", data: { turbo: false} do %>    
                            <div class="main-featured-card">
                                <div class="main-feature-content">
                                    <h2><%= @main_featured.headline %></h2>
                                    <p class="main-feature-description"><%= @main_featured.short_description %></p>
                                    <p class="main-feature-published"><%= time_ago_in_words(@main_featured.published_on) %> ago</p>
                                </div>
                                <div class="main-feature-image-box">
                                    <%= image_tag @main_featured.avatar.url, class: "main-feature-image" %>
                                </div>
                            </div>
                        <% end %> 
                    </div>
                    <div class="other-news-headlines">
                        <% @other_news.each do |other_news| %>
                            <%= link_to news_path(other_news), class: "other-news-link", data: { turbo: false} do %>    
                                <div class="other-news-card">
                                    <div class="other-news-image"><%= image_tag other_news.avatar.url, class: "news-image" %></div>
                                    <div class="other-news-content">
                                        <h3><%= other_news.headline %></h3>
                                        <p class="news-description"><%= other_news.short_description %></p>
                                        <div class="time-tag-display">
                                            <p class="news-published-on"><%= time_ago_in_words(other_news.published_on) %> ago</p>
                                            <p class="news-tag"><%= other_news.tag %></p>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                </div>
                <div class="news-sidebar-content">
                    <% @sidebar_news.each do |sidebar_news| %>
                        <%= link_to news_path(sidebar_news), class: "sidebar-news-link", data: { turbo: false} do %>    
                            <div class="sidebar-news-card">
                                <div class="sidebar-news-image"><%= image_tag sidebar_news.avatar.url, class: "sidebar-image" %></div>
                                <div class="sidebar-news-content">
                                    <h3><%= sidebar_news.headline %></h3>
                                    <p class="news-description"><%= sidebar_news.short_description %></p>
                                    <div class="time-tag-display">
                                        <p class="news-published-on"><%= time_ago_in_words(sidebar_news.published_on) %> ago</p>
                                        <p class="news-tag"><%= sidebar_news.tag %></p>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class= "more-news-section">
                <div class="more-news-heading">
                    <h3>More News</h3>
                </div>
                <div class="more-news-list">
                    <% @more_news.each do |more_news| %>
                        <div class="more-news-headline">
                            <%= link_to news_path(more_news), class: "more-news-link", data: { turbo: false} do %>
                                <h3> <%= more_news.headline %> </h3>  
                            <% end %>  
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </main>
    <%= render "partials/common_footer" %>
</body>