config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "newsroom", to: "application#newsroom"
  get "dashboard/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "application#newsroom"
  resources :book_reviews do 
    collection do 
      get :fiction
      get :history
      get :non_fiction
      get :mystery
      get :science
      get :romance
      get :spirituality
      get :fantasy
    end
  end
  resources :game_reviews
  resources :articles do
    collection do 
      get :culture
      get :travel
      get :sport
    end 
  end
  resources :news do 
    collection do 
      get :world
      get :sport
      get :regional
      get :tech
      get :business
      get :entertainment
    end
    member do
      get :comments
      post :news_comment
    end
  end
end

app/models/news.rb
class News < ApplicationRecord
    has_rich_text :content
    mount_uploader :avatar, AvatarUploader
    extend FriendlyId
    friendly_id :headline, use: :slugged
    has_many :comments, as: :commentable
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

    before_action :authenticate_user!
    before_action :load_news, only: [ :edit, :show, :comments, :news_comment]

    set_tab :news
    set_tab :world, :navigation, :only => %w(world)
    set_tab :sport, :navigation, :only => %w(sport)
    set_tab :regional, :navigation, :only => %w(regional)
    set_tab :tech, :navigation, :only => %w(tech)
    set_tab :business, :navigation, :only => %w(business)
    set_tab :entertainment, :navigation, :only => %w(entertainment)

    def index
        @main_featured = News.find_by(main_featured: true)
        @other_news = News.where(main_featured: false).order(created_at: :desc).limit(3)
        @sidebar_news = News.where(main_featured: false).where.not(id: @other_news.pluck(:id)).order(created_at: :desc).limit(2)
        exclude_ids = @other_news.pluck(:id) + @sidebar_news.pluck(:id)
        @more_news = News.where(main_featured: false).where.not(id: exclude_ids).order(created_at: :desc)
    end

    def world
        @main_featured = News.find_by(featured: true, tag: "World")
        @other_news = News.where(featured: false, tag: "World").order(created_at: :desc).limit(3)
        @sidebar_news = News.where(featured: false,  tag: "World").where.not(id: @other_news.pluck(:id)).order(created_at: :desc).limit(2)
        exclude_ids = @other_news.pluck(:id) + @sidebar_news.pluck(:id)
        @more_news = News.where(featured: false, tag: "World").where.not(id: exclude_ids).order(created_at: :desc)
    end

    def sport
        @main_featured = News.find_by(featured: true, tag: "Sport")
        @other_news = News.where(featured: false, tag: "Sport").order(created_at: :desc).limit(3)
        @sidebar_news = News.where(featured: false,  tag: "Sport").where.not(id: @other_news.pluck(:id)).order(created_at: :desc).limit(2)
        exclude_ids = @other_news.pluck(:id) + @sidebar_news.pluck(:id)
        @more_news = News.where(featured: false, tag: "Sport").where.not(id: exclude_ids).order(created_at: :desc) 
    end

    def regional
        @main_featured = News.find_by(featured: true, tag: "Regional")
        @other_news = News.where(featured: false, tag: "Regional").order(created_at: :desc).limit(3)
        @sidebar_news = News.where(featured: false,  tag: "Regional").where.not(id: @other_news.pluck(:id)).order(created_at: :desc).limit(2)
        exclude_ids = @other_news.pluck(:id) + @sidebar_news.pluck(:id)
        @more_news = News.where(featured: false, tag: "Regional").where.not(id: exclude_ids).order(created_at: :desc)
    end

    def tech
        @main_featured = News.find_by(featured: true, tag: "Tech")
        @other_news = News.where(featured: false, tag: "Tech").order(created_at: :desc).limit(3)
        @sidebar_news = News.where(featured: false,  tag: "Tech").where.not(id: @other_news.pluck(:id)).order(created_at: :desc).limit(2)
        exclude_ids = @other_news.pluck(:id) + @sidebar_news.pluck(:id)
        @more_news = News.where(featured: false, tag: "Tech").where.not(id: exclude_ids).order(created_at: :desc) 
    end 

    def business
        @main_featured = News.find_by(featured: true, tag: "Business")
        @other_news = News.where(featured: false, tag: "Business").order(created_at: :desc).limit(3)
        @sidebar_news = News.where(featured: false,  tag: "Business").where.not(id: @other_news.pluck(:id)).order(created_at: :desc).limit(2)
        exclude_ids = @other_news.pluck(:id) + @sidebar_news.pluck(:id)
        @more_news = News.where(featured: false, tag: "Business").where.not(id: exclude_ids).order(created_at: :desc)
    end

    def entertainment
        @main_featured = News.find_by(featured: true, tag: "Entertainment")
        @other_news = News.where(featured: false, tag: "Entertainment").order(created_at: :desc).limit(3)
        @sidebar_news = News.where(featured: false,  tag: "Entertainment").where.not(id: @other_news.pluck(:id)).order(created_at: :desc).limit(2)
        exclude_ids = @other_news.pluck(:id) + @sidebar_news.pluck(:id)
        @more_news = News.where(featured: false, tag: "Entertainment").where.not(id: exclude_ids).order(created_at: :desc)
    end

    def new
        @news = News.new
    end

    def edit
    end

    def show 
        @related = News.where(tag: @news.tag).where.not(id: @news.id).limit(6)
    end

    def create
        @news = News.new(news_params)
        if @news.save
            redirect_to news_index_path, notice: "News saved successfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        @news = News.find(params[:id])
        if @news.update(news_params)
            redirect_to news_path(@news), notice: "News updated successfully"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def comments
        @comment = Comment.new
        @comments = @news.comments
    end

    def news_comment
        @news.comments.create(comment: params[:comment][:comment], user_id: current_user.id)
        head :no_content
    end

    private

    def news_params
        params.require(:news).permit!
    end

    def load_news
        @news = News.friendly.find(params[:id])
    end
end

app/helpers/news_helper.rb
module NewsHelper
    
end

app/views/news/_all_comments.html.erb
<div class="news-comments-list">
    <% @comments.each do |x| %>
    <div class="comment-container">
        <div class="comment-details">
        <div class="comment-user">
            <%= "@#{x.user.first_name} #{x.user.surname}" %>
        </div>
        <div class="comment-time">
            <%= "#{time_ago_in_words(x.created_at)} ago" %>
        </div>
        </div>
        <div class="comment">  
        <%= action_text_links_new_tab(x.comment) %>
        </div>
    </div>
    <% end %>
</div>

app/views/news/business.html.erb
<%= render "partials/news_index", action: action_name %>

app/views/news/comments.html.erb
<turbo-frame id="modal">
  <% form_markup = capture do %>
    <div class="comments-popup-header">
      <h2>Comments</h2>
      <button type="button" class="comment-modal-close" aria-label="Close" data-action="click->modal#close">&times;</button>
    </div>
    <div class="comments-form">
      <%= form_for(@comment, url: news_comment_news_path, html: { method: :post }) do |f| %>
        <div class="field">
          <%= f.rich_text_area :comment %>
        </div>
        <div class="popup-actions">
          <button type="button" class=""> Cancel </button>   
          <%= f.submit "Comment", class: "", id: "" %>
        </div>
      <% end %>
    </div>
    <%= render "news/all_comments"%>
  <% end %>


  <% if turbo_frame_request? %>
    <div class="comment-modal-backdrop" data-action="click->modal#backgroundClick">
      <div class="comment-modal-dialog" data-action="click->modal#stopPropagation">
        <%= form_markup.html_safe %>
      </div>
    </div>
  <% else %>
    <div class="page-edit">
      <%= form_markup.html_safe %>
    </div>
  <% end %>

</turbo-frame>

app/views/news/edit.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <%= render "partials/news_form", url: news_path(@news), action: "Edit" %>
    </main>
</body>

app/views/news/entertainment.html.erb
<%= render "partials/news_index", action: action_name %>

app/views/news/index.html.erb
<%= render "partials/news_index", action: action_name %>

app/views/news/new.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <%= render "partials/news_form", url: news_index_path(@news), action: "New" %>
    </main>
</body>

app/views/news/regional.html.erb
<%= render "partials/news_index", action: action_name %>

app/views/news/show.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <div class="news-navigation">
            <div><%= link_to "Back", :back, class: "news-view-back", data: { turbo: false} %></div>
            <% if current_user.role == "Admin" %>
                <div class=""><%= link_to "Edit", edit_news_path(@news), class: "news-view-edit", data: { turbo: false} %></div>
            <% end %>
        </div>
        <div class="news-body">
            <div class="news-headline">
                <h1> <%= @news.headline %> </h1>
            </div>
            <div class="news-details">
                <p><%= time_ago_in_words(@news.published_on) %> ago</p>
            </div>
            <div class="news-main-image">
                <%= image_tag @news.avatar.url, class: "" %>
            </div>
            <div class="news-content">
                <%= action_text_links_new_tab(@news.content) %>
            </div>
            <%= link_to comments_news_path(@news), class: "news-comments", data: { turbo_frame: "modal" } do %>
                <div class="news-comments-section">
                    <%= icon "message-circle-more" %>
                    <h3> Comments </h3>
                </div>
            <% end %>
        </div>
        <% unless @related.empty? %>
            <div class= "more-news-section">
                <div class="more-news-heading">
                    <h3>Related </h3>
                </div>
                <div class="more-news-list">
                    <% @related.each do |related_news| %>
                        <div class="more-news-headline">
                            <%= link_to news_path(related_news), class: "more-news-link", data: { turbo: false} do %>
                                <h3> <%= related_news.headline %> </h3>  
                            <% end %>  
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </main>
    <%= render "partials/common_footer" %>
</body> 

app/views/news/sport.html.erb
<%= render "partials/news_index", action: action_name %>

app/views/news/tech.html.erb
<%= render "partials/news_index", action: action_name %>

app/views/news/world.html.erb
<%= render "partials/news_index", action: action_name %>