config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "newsroom", to: "application#newsroom"
  get "dashboard/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "application#newsroom"
  resources :book_reviews do 
    collection do 
      get :fiction
      get :history
      get :non_fiction
      get :mystery
      get :science
      get :romance
      get :spirituality
      get :fantasy
    end
  end
  resources :game_reviews
  resources :articles do
    collection do 
      get :culture
      get :travel
      get :sport
    end 
  end
  resources :news do 
    collection do 
      get :world
      get :sport
      get :regional
      get :tech
      get :business
      get :entertainment
    end
    member do
      get :comments
      post :news_comment
    end
  end
end

app/controllers/game_reviews_controller.rb
class GameReviewsController < ApplicationController
    before_action :authenticate_user!
    set_tab :game_reviews

    def index
        @game_reviews = GameReview.order(release: :desc).page(params[:page])
        @recent_Reviews = GameReview.order(created_at: :desc).limit(5)
    end

    def new
        @game_review = GameReview.new
    end

    def show
        @game_review = GameReview.friendly.find(params[:id])
    end

    def edit
        @game_review = GameReview.friendly.find(params[:id])
    end

    def create
        @game_review = GameReview.new(game_review_params)
        if @game_review.save
            redirect_to game_reviews_path, notice: "Review saved successfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        @game_review = GameReview.find(params[:id])
        if @game_review.update(game_review_params)
            redirect_to game_review_path(@game_review), notice: "Review updated successfully"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private 

    def game_review_params
        params.require(:game_review).permit!
    end
end

app/helpers/game_reviews_helper.rb
module GameReviewsHelper
    def ratings_helper(rating)
        if  rating >= 90
            return "Masterpiece"
        elsif rating >= 80  && rating < 90
            return "Amazing"
        elsif rating >= 70  && rating < 80
            return "Great"
        elsif rating >= 60  && rating < 70
            return "Good"      
        else
            return "Average"
        end
    end
end

app/views/game_reviews/edit.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <%= render "partials/game_review_form", url: game_review_path(@game_review), action: "edit" %>
    </main>
</body>

app/views/game_reviews/index.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <div class="sub-heading-header">
            <div class="tab-header">
                <h3> Game Reviews</h3>
            </div>
            <% if current_user.role == "Admin" %>
                <div class="add-new-container">
                    <%= icon "plus" %>
                    <span><%= link_to "Add Review", new_game_review_path, class: "add-new", data: { turbo: false} %></span>
                </div>
            <% end %>
        </div>
        <div class="general-main-content">
            <div class="left-main-content game-review-card-content">
                <% @game_reviews.each do |review| %>
                    <%= link_to game_review_path(review), class: "full-review-link", data: { turbo: false} do %>    
                        <div class="game-review-card">
                            <div class="review-image-box">
                                <%= image_tag review.avatar.url, class: "game-image" %>
                            </div>
                            <div class="review-content">
                                <h2><%= review.title %></h2>
                                <p class="review-description"><%= review.short_description %></p>
                                <p class="review-release"><%= review.release.strftime("%B %e, %Y") %></p>
                                <p class="review-rating"><%= review.rating %></p>
                            </div>
                        </div>
                    <% end %>    
                <% end %>
                <%= paginate @game_reviews %>
            </div>
            <div class="right-main-content">
                <div class="tab-heading-description">
                    <h3> About </h3>
                    <p> Find your next captivating gaming moment. Reviews about a wide variety of games across multiple genre's. Each review is scored to a maximim of 100, based on several factors and it's overall quality. </p>
                </div>
                <div class="sidebar-content">
                    <div class="sidebar-sub-header">
                        <h2> Recent Reviews </h2>
                    </div>
                    <% @recent_Reviews.each do |recent_review| %>
                        <div class="sidebar-review-card">
                            <div class="sidebar-image-box">
                                <%= image_tag recent_review.avatar.url, class: "sidebar-image" %>
                            </div>
                            <div class="sidebar-review-content">
                                <%= link_to game_review_path(recent_review), class: "full-review-link", data: { turbo: false} do %>
                                    <p class="review-title"><%= recent_review.title %><p>
                                <% end %>
                                <p class="review-release"><%= recent_review.release.strftime("%B %e, %Y") %></p>
                            </div>
                        </div>
                    <% end %>
                </div>
                <div class="index-page-sidebar-ad">
                    <p>ADVERTISEMENT</p>
                    <%= image_tag "heineken-ad.jpg", class: "sidebar-ad" %>
                </div>
            </div>
        </div>
    </main>
</body>

app/views/game_reviews/new.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <main class="sub-heading-content">
        <%= render "partials/game_review_form", url: game_reviews_path(@game_review), action: "new" %>
    </main>
</body>

app/views/game_reviews/show.html.erb
<body class="app-common-container">
    <%= render "partials/common_header" %>
    <div class="game-review-content">
        <div class="game-review-header">
            <div><%= link_to "Back", game_reviews_path, class: "game-review-back", data: { turbo: false} %></div>
            <% if current_user.role == "Admin" %>
                <div class=""><%= link_to "Edit", edit_game_review_path(@game_review), class: "game-review-edit", data: { turbo: false} %></div>
            <% end %>
        </div>
        <div class="game-review-body">
            <div class="game-review-title"><h1><%= @game_review.title %></h1></div>
            <div class="game-review-image">
                <%= image_tag @game_review.avatar.to_s, class:"game-image" %>
            </div>
            <div class="game-review-review">
                <%= action_text_links_new_tab(@game_review.review) %>
            </div>
            <div class="game-review-rating-container"> 
                <div class="game-review-rating"><%= @game_review.rating %></div>
            </div>
            <div class="game-review-text-verdict">
                <%= ratings_helper(@game_review.rating) %>
            </div>
        </div>
    </div>
    <%= render "partials/common_footer" %>
</body>